project_paint/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path

from app_sectors import views

urlpatterns = [
    # path("admin/", admin.site.urls, name ="admin"),
    path("", views.initial, name="initial"),
    path("cadastro/", views.home, name="home"),
    path("clientes/", views.clientes, name="clientes"),
    path("insumos/", views.insumos, name="insumos"),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

app_sectors/models.py
from django.db import models


class lista_clientes(models.Model):
    id_cliente = models.AutoField(primary_key=True)
    nome = models.TextField(max_length=255, default="Nome Padrão")
    idade = models.IntegerField()
    foto = models.ImageField(upload_to="fotos_clientes", blank=True, null=True)


class Produto(models.Model):
    nome = models.CharField(max_length=100)
    quantidade_disponivel = models.IntegerField()

app_sectors/views.py
from django.shortcuts import render

from .models import lista_clientes


def home(request):
    return render(request, "cadastro/index.html")


def initial(request):
    return render(request, "cadastro/home.html")


def insumos(request):
    return render(request, "cadastro/insumos.html")


def clientes(request):
    if request.method == "POST":
        novo_cliente = lista_clientes()
        novo_cliente.nome = request.POST.get("nome")
        novo_cliente.idade = request.POST.get("idade")
        novo_cliente.foto = request.FILES.get("foto")
        novo_cliente.save()

    clientes = {"clientes": lista_clientes.objects.all()}

    return render(request, "cadastro/clientes.html", clientes)

app_sectors/templates/cadastro/clientes.html
<!DOCTYPE html>
<html lang="pt_br">

<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Lista de Clientes</title>
</head>
<header>
  <h1>Lista de clientes</h1>
  <main>
    <a href="{% url 'home' %}" class="btn btn-primary">Página de cadastro</a>
    <a href="{% url 'clientes' %}" class="btn btn-primary">Página de clientes</a>
    <a href="{% url 'insumos' %}" class="btn btn-primary">Página de insumos</a>
    <a href="{% url 'initial' %}" class="btn btn-primary">Home</a>
  </main>
</header>

<div class="container">
  <table>
    <tr>
      <th>id</th>
      <th>nome</th>
      <th>idade</th>
      <th>foto</th>
    </tr>
    {%for cliente in clientes%}
    <tr>
      <td>{{cliente.id_cliente}}</td>
      <td>{{cliente.nome}}</td>
      <td>{{cliente.idade}}</td>
      <td><img src="{{ cliente.foto.url }}" alt="{{ cliente.nome }}" width="100"></td>
    </tr>
    {%endfor%}
  </table>
</div>

app_sectors/templates/cadastro/home.html
{% load static %}
<!DOCTYPE html>
<html lang="PT-br">

<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <link rel="stylesheet" type="text/css" href="{% static 'css/style1.css' %}">
  <title>HOME</title>
</head>

<body class="header-container">
  <header>
    <div>
      <h1>PINTURA AUTOMOTIVA</h1>
    </div>
    <div>
      <h1>ADMINISTRATIVO</h1>
    </div>

  </header>

  <main>
    <a href="{% url 'home' %}" class="btn btn-primary">Página de cadastro</a>
    <a href="{% url 'clientes' %}" class="btn btn-primary">Página de clientes</a>
    <a href="{% url 'insumos' %}" class="btn btn-primary">Página de insumos</a>
    <a href="{% url 'initial' %}" class="btn btn-primary">Home</a>
  </main>

</body>

</html>

app_sectors/templates/cadastro/index.html
{% load static %}

<div class="container">
  <h1>Cadastro de Clientes</h1>

  <main>
    <a href="{% url 'home' %}" class="btn btn-primary">Página de cadastro</a>
    <a href="{% url 'clientes' %}" class="btn btn-primary">Página de clientes</a>
    <a href="{% url 'insumos' %}" class="btn btn-primary">Página de insumos</a>
    <a href="{% url 'initial' %}" class="btn btn-primary">Home</a>
  </main>

  
  <form  action="{%url 'clientes'%}" method = "post" enctype="multipart/form-data">
    {% csrf_token %}
    <div>
      <label for="id_nome">Nome:</label>
      <input type="text" id="id_nome" name="nome" required>
    </div>
    <div>
      <label for="id_idade">Idade:</label>
      <input type="text" id="id_idade" name="idade" required>
    </div>
    <div>
      <label for="id_foto">Foto:</label>
      <input type="file" id="id_foto" name="foto" accept="image/*" required>
      <img id="preview" src="#" alt="Preview da Imagem" style="display: none; max-width: 200px; max-height: 200px;">
    </div>
    <button type="submit">Enviar</button>
  </form>
</div>

<script>
  // Função para pré-visualizar a imagem antes de enviá-la
  function previewImage(input) {
    if (input.files && input.files[0]) {
      var reader = new FileReader();

      reader.onload = function (e) {
        document.getElementById('preview').style.display = 'block';
        document.getElementById('preview').src = e.target.result;
      }

      reader.readAsDataURL(input.files[0]);
    }
  }

  // Event listener para chamar a função de pré-visualização quando o usuário seleciona uma imagem
  document.getElementById('id_foto').addEventListener('change', function() {
    previewImage(this);
  });
</script>

app_sectors/templates/cadastro/insumos.html
<!DOCTYPE html>
<html lang="PT-br">



<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Document</title>
</head>

<h1>Insumos</h1>
<main>
  <a href="{% url 'home' %}" class="btn btn-primary">Página de cadastro</a>
  <a href="{% url 'clientes' %}" class="btn btn-primary">Página de clientes</a>
  <a href="{% url 'insumos' %}" class="btn btn-primary">Página de insumos</a>
  <a href="{% url 'initial' %}" class="btn btn-primary">Home</a>
</main>

<body>


</body>

</html>